#Localhost | Running on port 8080
##Local Deployment


##getAll Contact
GET http://localhost:8080/contacts


### getSingle contact by id
GET http://localhost:8080/contacts/67d773636af74303a5dc1d3b


### Create contact 
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}

### PUT contact
PUT http://localhost:8080/contacts/67d773636af74303a5dc1d3b HTTP/1.1
content-type: application/json

{
  "firstName": "Phiona",
  "lastName": "Amoah Scott",
  "email": "raphaeltesting@test.com",
  "favoriteColor": "Grey",
  "birthday": "02/01/2009"
}
### DELETE contact
DELETE http://localhost:8080/contacts/67d773636af74303a5dc1d3b HTTP/1.1





// Render.com production Deployment
### Get all contacts
GET https://contacts-1v6q.onrender.com/contacts


### Get contact by id
GET https://contacts-1v6q.onrender.com/contacts/622023f642f9ab4cd6e060b3


### Create contact
POST https://contacts-1v6q.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT contact
PUT https://contacts-1v6q.onrender.com/contacts/67d773d56af74303a5dc1d3c HTTP/1.1
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Birch",
    "email":"sarahB@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"06/12/20"
}


### DELETE contact
DELETE https://contacts-1v6q.onrender.com/contacts/622023f642f9ab4cd6e060b3 HTTP/1.1